Update Spanish Translation
siavash79/AOSPMods pull request #514
Opened 2023-01-03 12:21 UTC by tomaja18

Update Spanish Translation

2023-01-03 14:34 UTC, EleoXDA commented
Please remove "untranslatable" lines from translation. We have to remove them everytime manually.

2023-01-03 14:35 UTC, EleoXDA requested changes

2023-01-03 14:35 UTC, EleoXDA commented on app/src/main/res/values-es/strings.xml
> +	<string name="app_name" translatable="false">AOSP Mods</string>
Please remove all the "untranslatable" lines from translation. We have to remove them everytime manually.

2023-01-03 16:25 UTC, tomaja18 commented on app/src/main/res/values-es/strings.xml
> +	<string name="app_name" translatable="false">AOSP Mods</string>
It is already corrected

2023-01-03 16:46 UTC, EleoXDA commented
Why did you close the pull request? Please reopen it so that we can merge it

2023-01-03 16:56 UTC, tomaja18 commented
I think that's it, I don't know the platform very well, sorry.

2023-01-03 17:09 UTC, tomaja18 commented
Ok, I think that is now correct.

2023-01-05 07:57 UTC, EleoXDA approved these changes
Ok

2023-01-05 07:59 UTC, merged